### ISSUE TITLE
Reason for GPL ?

### ISSUE THREAD

**Issue by ahoarau** [MRASL/mrasl_mav_traj#2]
Hi and thanks for the good work !
I was wondering why you chose GPL over something a bit more permissive like LGPL.
Companies and research facilities are running away from GPL code nowadays.

**Comment by andre-nguyen** [comment]
Good question, the reason was that the community edition of ALGLIB is GPL licensed and so I guess we have to be and the reason the project includes it was just for solver comparison purposes. However, as mentioned in the readme, we don't even need optimization solvers as I had never gotten to implementing corridor constraints in the problem. Without those constraints, the problem is convex and only has equality constraints which means we could just use eigen to invert the matrix and remove ALGLIB altogether and even support for all the other solvers.

In essence, if you can send a PR to remove ALGLIB I can relicense this under MIT or BSD.

Edit: We still need a solver for the time allocation though.
